//login types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

//signup types
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_NOTIFICATION_DISPLAYED = "SIGN_UP_NOTIFICATION_DISPLAYED";

//movie schedules
export const CREATE_MOVIESCHEDULES = "CREATE_MOVIESCHEDULES";
export const ADD_MOVIESCHEDULES = "ADD_MOVIESCHEDULES";
export const UPDATE_MOVIESCHEDULES = "UPDATE_MOVIESCHEDULES";
export const GET_MOVIESCHEDULES = "GET_MOVIESCHEDULES";
export const DELETE_MOVIESCHEDULES = "DELETE_MOVIESCHEDULES";
export const SELECT_MOVIESCHEDULES = "SELECT_MOVIESCHEDULES";
export const SELECT_ALL_MOVIESCHEDULES = "SELECT_ALL_MOVIESCHEDULES";

//Reservas
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_RESERVATION_SEATS = "GET_RESERVATION_SEATS";
