//login types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

//signup types
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_NOTIFICATION_DISPLAYED = "SIGN_UP_NOTIFICATION_DISPLAYED";

//movie schedules
export const GET_SHOWTIMES = "GET_SHOWTIMES";
export const ADD_SHOWTIME = "ADD_SHOWTIME";
export const UPDATE_SHOWTIME = "UPDATE_SHOWTIME";
export const DELETE_SHOWTIME = "DELETE_SHOWTIME";
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";
export const SELECT_SHOWTIMES = "SELECT_SHOWTIMES";
export const SELECT_ALL_SHOWTIMES = "SELECT_ALL_SHOWTIMES";

//Reservas
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_RESERVATION_SEATS = "GET_RESERVATION_SEATS";

//ticket
export const SET_SELECTED_SEATS = "SET_SELECTED_SEATS";
export const SET_SUGGESTED_SEATS = "SET_SUGGESTED_SEATS";
export const SET_SELECTED_CINEMA = "SET_SELECTED_CINEMA";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_TIME = "SET_SELECTED_TIME";
export const TOGGLE_LOGIN_POPUP = "TOGGLE_LOGIN_POPUP";
export const SHOW_INVITATION_FORM = "SHOW_INVITATION_FORM";
export const SET_INVITATION = "SET_INVITATION";
export const SET_QR_CODE = "SET_QR_CODE";
export const RESET_CHECKOUT = "RESET_CHECKOUT";

//alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
